"""empty message

Revision ID: 706a278d6d80
Revises: a053beba6668
Create Date: 2025-02-15 14:29:08.165799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706a278d6d80'
down_revision = 'a053beba6668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(), nullable=False))
        batch_op.drop_column('planet_climate')
        batch_op.drop_column('planet_name')
        batch_op.drop_column('planet_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planet_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_climate', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('url')
        batch_op.drop_column('climate')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
