"""empty message

Revision ID: 769bc1951570
Revises: fa5a64205548
Create Date: 2025-02-15 15:19:29.635348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769bc1951570'
down_revision = 'fa5a64205548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vehicle_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicle_pkey')
    )
    # ### end Alembic commands ###
