"""empty message

Revision ID: a053beba6668
Revises: bdf9ec328e14
Create Date: 2025-02-15 14:11:12.963359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a053beba6668'
down_revision = 'bdf9ec328e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('race', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(), nullable=True))
        batch_op.drop_column('character_name')
        batch_op.drop_column('character_race')
        batch_op.drop_column('character_age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_age', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_race', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('character_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('age')
        batch_op.drop_column('race')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
