"""empty message

Revision ID: b15c08cffcc7
Revises: cb9de99d5196
Create Date: 2025-02-14 11:46:54.654350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15c08cffcc7'
down_revision = 'cb9de99d5196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(), nullable=True),
    sa.Column('planet_climate', sa.String(), nullable=False),
    sa.Column('planet_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
